/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit records. */
        get: operations["list_audit_records"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an audit record by id. */
        get: operations["get_audit_record"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain an authorization decision. */
        post: operations["explain_auth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cameras. */
        get: operations["list_cameras"];
        put?: never;
        /** Create a camera. */
        post: operations["create_camera"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a camera by id. */
        get: operations["get_camera"];
        put?: never;
        post?: never;
        /** Delete a camera. */
        delete: operations["delete_camera"];
        options?: never;
        head?: never;
        /** Update a camera. */
        patch: operations["update_camera"];
        trace?: never;
    };
    "/config-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configuration definitions. */
        get: operations["list_config_definitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config-definitions/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a configuration definition by key. */
        get: operations["get_config_definition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configuration values. */
        get: operations["list_config_values"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config-values/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a configuration value by id. */
        get: operations["get_config_value"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a configuration value. */
        patch: operations["update_config_value"];
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List managed devices. */
        get: operations["list_devices"];
        put?: never;
        /** Create a managed device. */
        post: operations["create_device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a managed device by id. */
        get: operations["get_device"];
        put?: never;
        post?: never;
        /** Delete a managed device. */
        delete: operations["delete_device"];
        options?: never;
        head?: never;
        /** Update a managed device. */
        patch: operations["update_device"];
        trace?: never;
    };
    "/devices/{id}/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change a device lifecycle. */
        post: operations["change_device_lifecycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List external bindings. */
        get: operations["list_external_bindings"];
        put?: never;
        /** Create an external binding. */
        post: operations["create_external_binding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-bindings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an external binding. */
        delete: operations["delete_external_binding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-bindings/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve an external binding conflict. */
        post: operations["resolve_external_binding_conflict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check handler. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization-units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization units. */
        get: operations["list_organization_units"];
        put?: never;
        /** Create an organization unit. */
        post: operations["create_organization_unit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization-units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an organization unit by id. */
        get: operations["get_organization_unit"];
        put?: never;
        post?: never;
        /** Delete an organization unit. */
        delete: operations["delete_organization_unit"];
        options?: never;
        head?: never;
        /** Update an organization unit. */
        patch: operations["update_organization_unit"];
        trace?: never;
    };
    "/organization-units/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move an organization unit. */
        post: operations["move_organization_unit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projection states. */
        get: operations["list_projections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List role bindings. */
        get: operations["list_role_bindings"];
        put?: never;
        /** Create a role binding. */
        post: operations["create_role_binding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/role-bindings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a role binding by id. */
        get: operations["get_role_binding"];
        put?: never;
        post?: never;
        /** Delete a role binding. */
        delete: operations["delete_role_binding"];
        options?: never;
        head?: never;
        /** Update a role binding. */
        patch: operations["update_role_binding"];
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles. */
        get: operations["list_roles"];
        put?: never;
        /** Create a role. */
        post: operations["create_role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a role by id. */
        get: operations["get_role"];
        put?: never;
        post?: never;
        /** Delete a role. */
        delete: operations["delete_role"];
        options?: never;
        head?: never;
        /** Update a role. */
        patch: operations["update_role"];
        trace?: never;
    };
    "/service-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a service account. */
        post: operations["create_service_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spatial-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List spatial nodes. */
        get: operations["list_spatial_nodes"];
        put?: never;
        /** Create a spatial node. */
        post: operations["create_spatial_node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spatial-nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a spatial node by id. */
        get: operations["get_spatial_node"];
        put?: never;
        post?: never;
        /** Delete a spatial node. */
        delete: operations["delete_spatial_node"];
        options?: never;
        head?: never;
        /** Update a spatial node. */
        patch: operations["update_spatial_node"];
        trace?: never;
    };
    "/spatial-nodes/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a spatial node. */
        post: operations["move_spatial_node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags for a resource. */
        get: operations["list_tags"];
        put?: never;
        /** Create a tag. */
        post: operations["create_tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a tag. */
        delete: operations["delete_tag"];
        options?: never;
        head?: never;
        /** Update a tag. */
        patch: operations["update_tag"];
        trace?: never;
    };
    "/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant by id. */
        get: operations["get_tenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users. */
        get: operations["list_users"];
        put?: never;
        /** Create a user. */
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by id. */
        get: operations["get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a user. */
        patch: operations["update_user"];
        trace?: never;
    };
    "/users/{id}/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manage a user's MFA. */
        post: operations["manage_user_mfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a user's password. */
        post: operations["set_user_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change a user's status. */
        post: operations["change_user_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response containing a newly created API key (shown once). */
        ApiKeyCreatedDto: {
            expiresAt?: string | null;
            id: string;
            key: string;
            name: string;
            scopes: string[];
            tenantId: string;
        };
        /** @description Stable API representation of audit record details. */
        AuditDetailsDto: {
            schema: string;
            value: unknown;
        };
        /** @description Stable API representation of an audit record. */
        AuditRecordDto: {
            action: string;
            actorId: string;
            actorType: string;
            afterDigest?: string | null;
            beforeDigest?: string | null;
            details: components["schemas"]["AuditDetailsDto"];
            id?: string | null;
            occurredAt: string;
            requestId?: string | null;
            result: string;
            risk: string;
            sourceIp?: string | null;
            targetId: string;
            targetType: string;
            tenantId: string;
            traceId?: string | null;
        };
        /** @description Request to preview an authorization decision. */
        AuthExplainRequest: {
            action: string;
            principalId: string;
            resourceId: string;
            resourceType: string;
        };
        /** @description Authorization explanation. */
        AuthExplainResponse: {
            decision: string;
            reason: string;
        };
        /** @description Stable API representation of a camera. */
        CameraDto: {
            actor?: string | null;
            areaId?: string | null;
            code: string;
            createdAt: string;
            deviceId: string;
            id: string;
            isEnabled: boolean;
            name: string;
            /** Format: int64 */
            revision: number;
            sensitivity: string;
            tenantId: string;
            updatedAt: string;
        };
        /** @description Request to change a device lifecycle. */
        ChangeDeviceLifecycleRequest: {
            /** Format: int64 */
            expectedRevision: number;
            lifecycle: string;
        };
        /** @description Request to change a user status. */
        ChangeUserStatusRequest: {
            /** Format: int64 */
            expectedRevision: number;
            status: string;
        };
        /** @description Stable API representation of a configuration definition. */
        ConfigDefinitionDto: {
            configKey: string;
            defaultValue: string;
            dynamic: boolean;
            schema?: string | null;
            sensitive: boolean;
            valueType: string;
        };
        /** @description Stable API representation of a configuration scope. */
        ConfigScopeDto: {
            /** @enum {string} */
            kind: "platform";
        } | {
            /** @enum {string} */
            kind: "tenant";
            tenant_id: string;
        } | {
            /** @enum {string} */
            kind: "module";
            module: string;
            tenant_id: string;
        };
        /** @description Stable API representation of a configuration value. */
        ConfigValueDto: {
            configKey: string;
            id?: string | null;
            /** Format: int64 */
            revision: number;
            scope: components["schemas"]["ConfigScopeDto"];
            secretRef?: string | null;
            value: string;
        };
        /** @description Request to create a camera. */
        CreateCameraRequest: {
            areaId?: string | null;
            code: string;
            deviceId: string;
            name: string;
            sensitivity: string;
        };
        /** @description Request to create a managed device. */
        CreateDeviceRequest: {
            areaId?: string | null;
            code: string;
            name: string;
            organizationId?: string | null;
            serial?: string | null;
        };
        /** @description Request to create an external binding. */
        CreateExternalBindingRequest: {
            externalKind: string;
            externalRef: string;
            resourceId: string;
            resourceType: string;
        };
        /** @description Request to create an organization unit. */
        CreateOrganizationUnitRequest: {
            code: string;
            name: string;
            parentId?: string | null;
        };
        /** @description Request to create a role binding. */
        CreateRoleBindingRequest: {
            principalId: string;
            roleId: string;
            scope: components["schemas"]["RoleBindingScopeDto"];
            validFrom: string;
            validUntil?: string | null;
        };
        /** @description Request to create a role. */
        CreateRoleRequest: {
            name: string;
            permissions: string[];
        };
        /** @description Request to create a service account. */
        CreateServiceAccountRequest: {
            name: string;
        };
        /** @description Request to create a spatial node. */
        CreateSpatialNodeRequest: {
            code: string;
            name: string;
            nodeType: components["schemas"]["SpatialNodeType"];
            parentId?: string | null;
        };
        /** @description Request to create a tag. */
        CreateTagRequest: {
            key: string;
            resourceId: string;
            resourceType: string;
            value: string;
        };
        /** @description Request to create a user. */
        CreateUserRequest: {
            displayName: string;
            username: string;
        };
        /** @description Stable API representation of a managed device. */
        DeviceDto: {
            actor?: string | null;
            areaId?: string | null;
            code: string;
            createdAt: string;
            id: string;
            lifecycle: string;
            name: string;
            onlineState: string;
            organizationId?: string | null;
            /** Format: int64 */
            revision: number;
            serial?: string | null;
            tenantId: string;
            updatedAt: string;
        };
        /** @description Stable API representation of an external binding. */
        ExternalBindingDto: {
            activatedAt?: string | null;
            actor?: string | null;
            createdAt: string;
            externalKind: string;
            externalRef: string;
            id: string;
            resourceId: string;
            resourceType: string;
            /** Format: int64 */
            revision: number;
            state: string;
            tenantId: string;
            updatedAt: string;
        };
        /** @description Health status returned by the root endpoint. */
        HealthDto: {
            component: string;
            status: string;
        };
        /** @description Request to enable or disable MFA. */
        ManageMfaRequest: {
            enabled: boolean;
            /** Format: int64 */
            expectedRevision: number;
        };
        /** @description Request to move an organization unit. */
        MoveOrganizationUnitRequest: {
            /** Format: int64 */
            expectedRevision: number;
            parentId?: string | null;
        };
        /** @description Request to move a spatial node. */
        MoveSpatialNodeRequest: {
            /** Format: int64 */
            expectedRevision: number;
            parentId?: string | null;
        };
        /** @description Stable API representation of an organization unit. */
        OrganizationUnitDto: {
            actor?: string | null;
            code: string;
            createdAt: string;
            id: string;
            name: string;
            parentId?: string | null;
            /** Format: int64 */
            revision: number;
            tenantId: string;
            updatedAt: string;
        };
        /** @description Generic API problem details sent by this service. */
        ProblemDetailsDto: {
            detail: string;
            instance?: string | null;
            /** Format: int32 */
            status: number;
            title: string;
            type: string;
        };
        /** @description Stable API representation of a projection node. */
        ProjectionStateDto: {
            channelId: string;
            deviceId: string;
            isOnline: boolean;
            isStale: boolean;
            observedAt: string;
            tenantId: string;
        };
        /** @description Request to resolve an external binding conflict. */
        ResolveExternalBindingConflictRequest: {
            action: string;
            /** Format: int64 */
            expectedRevision: number;
        };
        /** @description Stable API representation of an explicit resource reference. */
        ResourceRefDto: {
            resourceId: string;
            resourceType: string;
        };
        /** @description Stable API representation of a role binding. */
        RoleBindingDto: {
            actor?: string | null;
            createdAt: string;
            id: string;
            principalId: string;
            /** Format: int64 */
            revision: number;
            roleId: string;
            scope: components["schemas"]["RoleBindingScopeDto"];
            tenantId: string;
            updatedAt: string;
            validFrom: string;
            validUntil?: string | null;
        };
        /** @description Stable API representation of a role-binding scope. */
        RoleBindingScopeDto: {
            /** @enum {string} */
            kind: "tenant";
        } | {
            /** @enum {string} */
            kind: "organization_subtree";
            resource_id: string;
        } | {
            /** @enum {string} */
            kind: "area_subtree";
            resource_id: string;
        } | {
            /** @enum {string} */
            kind: "resource_set";
            resources: components["schemas"]["ResourceRefDto"][];
        };
        /** @description Stable API representation of a role. */
        RoleDto: {
            actor?: string | null;
            createdAt: string;
            id: string;
            isBuiltin: boolean;
            name: string;
            permissions: string[];
            /** Format: int64 */
            revision: number;
            tenantId?: string | null;
            updatedAt: string;
        };
        /** @description Request to set a user's password. */
        SetPasswordRequest: {
            /** Format: int64 */
            expectedRevision: number;
            password: string;
        };
        /** @description Stable API representation of a spatial node. */
        SpatialNodeDto: {
            actor?: string | null;
            code: string;
            createdAt: string;
            id: string;
            name: string;
            nodeType: components["schemas"]["SpatialNodeType"];
            parentId?: string | null;
            /** Format: int64 */
            revision: number;
            tenantId: string;
            updatedAt: string;
        };
        /**
         * @description Spatial node kind.
         * @enum {string}
         */
        SpatialNodeType: "site" | "building" | "floor" | "area";
        /** @description Stable API representation of a tag. */
        TagDto: {
            actor?: string | null;
            createdAt: string;
            id: string;
            key: string;
            resourceId: string;
            resourceType: string;
            /** Format: int64 */
            revision: number;
            tenantId: string;
            updatedAt: string;
            value: string;
        };
        /** @description Stable API representation of a tenant. */
        TenantDto: {
            actor?: string | null;
            code: string;
            createdAt: string;
            id: string;
            locale: string;
            name: string;
            /** Format: int64 */
            revision: number;
            status: string;
            timezone: string;
            updatedAt: string;
        };
        /** @description Request to update a camera. */
        UpdateCameraRequest: {
            areaId?: string | null;
            /** Format: int64 */
            expectedRevision: number;
            isEnabled: boolean;
            name: string;
            sensitivity: string;
        };
        /** @description Request to update a configuration value. */
        UpdateConfigValueRequest: {
            clearSecret: boolean;
            /** Format: int64 */
            expectedRevision: number;
            value?: string | null;
        };
        /** @description Request to update a managed device. */
        UpdateDeviceRequest: {
            areaId?: string | null;
            /** Format: int64 */
            expectedRevision: number;
            name: string;
            organizationId?: string | null;
            serial?: string | null;
        };
        /** @description Request to update an organization unit. */
        UpdateOrganizationUnitRequest: {
            /** Format: int64 */
            expectedRevision: number;
            name: string;
        };
        /** @description Request to update a role binding. */
        UpdateRoleBindingRequest: {
            /** Format: int64 */
            expectedRevision: number;
            roleId: string;
            scope: components["schemas"]["RoleBindingScopeDto"];
            validFrom: string;
            validUntil?: string | null;
        };
        /** @description Request to update a role. */
        UpdateRoleRequest: {
            /** Format: int64 */
            expectedRevision: number;
            name: string;
            permissions: string[];
        };
        /** @description Request to update a spatial node. */
        UpdateSpatialNodeRequest: {
            /** Format: int64 */
            expectedRevision: number;
            name: string;
        };
        /** @description Request to update a tag. */
        UpdateTagRequest: {
            /** Format: int64 */
            expectedRevision: number;
            value: string;
        };
        /** @description Request to update a user. */
        UpdateUserRequest: {
            displayName: string;
            /** Format: int64 */
            expectedRevision: number;
        };
        /** @description Stable API representation of a user. */
        UserDto: {
            actor?: string | null;
            createdAt: string;
            deletedAt?: string | null;
            displayName: string;
            id: string;
            /** Format: int64 */
            revision: number;
            /** Format: int64 */
            sessionVersion: number;
            status: string;
            tenantId: string;
            updatedAt: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_records: {
        parameters: {
            query?: {
                /** @description Target type */
                targetType?: string;
                /** @description Target ID */
                targetId?: string;
                /** @description Action filter */
                action?: string;
                /** @description Start time (RFC 3339) */
                from?: string;
                /** @description End time (RFC 3339) */
                to?: string;
                /** @description Search term */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecordDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_audit_record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecordDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    explain_auth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthExplainRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthExplainResponse"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_cameras: {
        parameters: {
            query?: {
                /** @description Search term */
                search?: string;
                /** @description Device filter */
                deviceId?: string;
                /** @description Area filter */
                areaId?: string;
                /** @description Sensitivity filter */
                sensitivity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    create_camera: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCameraRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_camera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    delete_camera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    update_camera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCameraRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_config_definitions: {
        parameters: {
            query?: {
                /** @description Module filter */
                module?: string;
                /** @description Search term */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDefinitionDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_config_definition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDefinitionDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_config_values: {
        parameters: {
            query?: {
                /** @description Module filter */
                module?: string;
                /** @description Search term */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValueDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_config_value: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValueDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    update_config_value: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConfigValueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValueDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_devices: {
        parameters: {
            query?: {
                /** @description Search term */
                search?: string;
                /** @description Organization filter */
                organizationId?: string;
                /** @description Area filter */
                areaId?: string;
                /** @description Lifecycle filter */
                lifecycle?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    create_device: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    delete_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    update_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeviceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    change_device_lifecycle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeDeviceLifecycleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_external_bindings: {
        parameters: {
            query?: {
                /** @description Resource type */
                resourceType?: string;
                /** @description Resource ID */
                resourceId?: string;
                /** @description Search term */
                search?: string;
                /** @description State filter */
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalBindingDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    create_external_binding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExternalBindingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalBindingDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    delete_external_binding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    resolve_external_binding_conflict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveExternalBindingConflictRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalBindingDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    list_organization_units: {
        parameters: {
            query?: {
                /** @description Filter by parent id */
                parentId?: string;
                /** @description Search term */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationUnitDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    create_organization_unit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationUnitRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationUnitDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_organization_unit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationUnitDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    delete_organization_unit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    update_organization_unit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationUnitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationUnitDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    move_organization_unit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveOrganizationUnitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationUnitDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_projections: {
        parameters: {
            query?: {
                /** @description Device filter */
                deviceId?: string;
                /** @description Stale filter */
                isStale?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionStateDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_role_bindings: {
        parameters: {
            query?: {
                /** @description Search term */
                search?: string;
                /** @description Principal filter */
                principalId?: string;
                /** @description Role filter */
                roleId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleBindingDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    create_role_binding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleBindingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleBindingDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_role_binding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleBindingDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    delete_role_binding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    update_role_binding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleBindingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleBindingDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_roles: {
        parameters: {
            query?: {
                /** @description Search term */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    create_role: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_role: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    delete_role: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    update_role: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    create_service_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceAccountRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreatedDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_spatial_nodes: {
        parameters: {
            query?: {
                /** @description Filter by parent id */
                parentId?: string;
                /** @description Search term */
                search?: string;
                /** @description Filter by node type */
                nodeType?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialNodeDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    create_spatial_node: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpatialNodeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialNodeDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_spatial_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialNodeDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    delete_spatial_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    update_spatial_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSpatialNodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialNodeDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    move_spatial_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveSpatialNodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialNodeDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_tags: {
        parameters: {
            query?: {
                /** @description Resource type */
                resourceType?: string;
                /** @description Resource ID */
                resourceId?: string;
                /** @description Search term */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    create_tag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    delete_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    update_tag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_tenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: {
                /** @description Search term */
                search?: string;
                /** @description User status */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    manage_user_mfa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManageMfaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    set_user_password: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    change_user_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeUserStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
}
